--- 
education: |-
    4 GCSEs
    3 A-Levels
    BSc in the Internet of Things
employed: true
foods: 
  - Apple
  - Orange
  - Strawberry
  - Mango
job: "senior Developer"
languages: 
  pascal: Lame
  perl: Elite
  python: Elite
skill: Elite

